---
 - name: My Website
   hosts: ubuntu
   become: yes

   vars:
    source_file : ./MyWebsite/index.html
    dest_file   : /var/www/html/

   tasks:
    - name: Install Apache
      apt: name=apache2 state=latest
    
    - name: Move my index
      copy: src={{ source_file }} dest={{ dest_file }} mode=0555
      notify: Restart_Apache
    
    - name: Enable after reboot
      service: name=apache2 state=started enabled=yes
    
   handlers:
    - name: Restart_Apache
      service: name=apache2 state=restarted

