---
 - name : Setup Apache
   hosts : ubuntu
   become: yes
 
   tasks:
    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Run after reboot system
      service: name=apache2 state=started enabled=yes


